[package]
authors = ["The Rust Project Developers"]
build = "build.rs"
name = "rustc_lsan"
version = "0.0.0"

[lib]
name = "rustc_lsan"
path = "lib.rs"

[build-dependencies]
cmake = "0.1.18"

[dependencies]
alloc_system = { path = "../liballoc_system" }
core = { path = "../libcore" }
