[package]
authors = ["The Rust Project Developers"]
name = "rustc_save_analysis"
version = "0.0.0"

[lib]
name = "rustc_save_analysis"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
log = { path = "../liblog" }
rustc = { path = "../librustc" }
syntax = { path = "../libsyntax" }
# FIXME should move rustc serialize out of tree
rustc-serialize = "0.3"
syntax_pos = { path = "../libsyntax_pos" }
rls-data = { git = "https://github.com/nrc/rls-data" }
